[eeg]
montage = "biosemi64"

[eeg.chans]
eeg = []
eog = ["EOGL", "EOGR", "EOGT", "EOGB"]
stim = 'Status'

[eeg.ch_groups]
all = [
    'Fp1',
    'AF7',
    'AF3',
    'F1',
    'F3',
    'F5',
    'F7',
    'FT7',
    'FC5',
    'FC3',
    'FC1',
    'C1',
    'C3',
    'C5',
    'T7',
    'TP7',
    'CP5',
    'CP3',
    'CP1',
    'P1',
    'P3',
    'P5',
    'P7',
    'P9',
    'PO7',
    'PO3',
    'O1',
    'Iz',
    'Oz',
    'POz',
    'Pz',
    'CPz',
    'Fpz',
    'Fp2',
    'AF8',
    'AF4',
    'AFz',
    'Fz',
    'F2',
    'F4',
    'F6',
    'F8',
    'FT8',
    'FC6',
    'FC4',
    'FC2',
    'FCz',
    'Cz',
    'C2',
    'C4',
    'C6',
    'T8',
    'TP8',
    'CP6',
    'CP4',
    'CP2',
    'P2',
    'P4',
    'P6',
    'P8',
    'P10',
    'PO8',
    'PO4',
    'O2',
]
frontal = [
    "Fp1",
    "Fpz",
    "Fp2",
    "AF7",
    "AF3",
    "AFz",
    "AF4",
    "AF8",
    "F7",
    "F5",
    "F3",
    "F1",
    "Fz",
    "F2",
    "F4",
    "F6",
    "F8",
]
central = [
    "FC5",
    "FC3",
    "FC1",
    "FCz",
    "FC2",
    "FC4",
    "FC6",
    "C5",
    "C3",
    "C1",
    "Cz",
    "C2",
    "C4",
    "C6",
]
temporal = ["FT7", "T7", "TP7", "FT8", "T8", "TP8"]
parietal = [
    "CP5",
    "CP3",
    "CP1",
    "CPz",
    "CP2",
    "CP4",
    "CP6",
    "P5",
    "P3",
    "P1",
    "Pz",
    "P2",
    "P4",
    "P6",
]
occipital = [
    "P7",
    "P8",
    "P9",
    "PO7",
    "PO3",
    "POz",
    "PO4",
    "PO8",
    "P10",
    "Oz",
    "Iz",
    "O1",
    "O2",
]
fronto-temporal = [
    "F7",
    "F5",
    "F3",
    "F1",
    "Fz",
    "F2",
    "F4",
    "F6",
    "F8",
    "FT7",
    "T7",
    "TP7",
    "FT8",
    "T8",
    "TP8",
]
fronto-central = [
    "F3",
    "F1",
    "Fz",
    "F2",
    "F4",
    "FC5",
    "FC3",
    "FC1",
    "FCz",
    "FC2",
    "FC4",
    "FC6",
]
centro-parietal = [
    "C5",
    "C3",
    "C1",
    "Cz",
    "C2",
    "C4",
    "C6",
    "CP5",
    "CP3",
    "CP1",
    "CPz",
    "CP2",
    "CP4",
    "CP6",
    "P5",
    "P3",
    "P1",
    "Pz",
    "P2",
    "P4",
    "P6",
]

[eeg.bad_channels]
[eeg.bad_channels.subj_1]
sess_1 = ["F3", "Fp1"]
sess_2 = []
sess_3 = []
sess_4 = ["T8", "AF8", "F8", "P7"]
sess_5 = []

[eeg.bad_channels.subj_2]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []

[eeg.bad_channels.subj_3]
sess_1 = ["Iz", "AF3"]
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []

[eeg.bad_channels.subj_4]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []

[eeg.bad_channels.subj_5]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []

[eeg.bad_channels.subj_6]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []


[eeg.bad_channels.subj_7]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []


[eeg.bad_channels.subj_8]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []

[eeg.bad_channels.subj_9]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []

[eeg.bad_channels.subj_10]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []

[eeg.bad_channels.subj_11]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []

[eeg.bad_channels.subj_12]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []


[eeg.bad_channels.subj_13]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []


[eeg.bad_channels.subj_14]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []


[eeg.bad_channels.subj_15]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []


[eeg.bad_channels.subj_16]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []


[eeg.bad_channels.subj_17]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []


[eeg.bad_channels.subj_18]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []


[eeg.bad_channels.subj_19]
sess_1 = []
sess_2 = []
sess_3 = []
sess_4 = []
sess_5 = []


[stim]
[stim.x_pos_stim]
# * Manually extracted from experiment's script
items_set = [
    -1042.222,
    -744.444,
    -446.667,
    -148.889,
    148.889,
    446.667,
    744.444,
    1042.222,
]

avail_choice = [
    -446.66700000000003,
    -148.88900000000012,
    148.88900000000012,
    446.6669999999999,
]
