[eeg]
[eeg.ch_groups]
frontal = [
    "Fp1",
    "Fpz",
    "Fp2",
    "AF7",
    "AF3",
    "AFz",
    "AF4",
    "AF8",
    "F7",
    "F5",
    "F3",
    "F1",
    "Fz",
    "F2",
    "F4",
    "F6",
    "F8",
]
central = [
    "FC5",
    "FC3",
    "FC1",
    "FCz",
    "FC2",
    "FC4",
    "FC6",
    "C5",
    "C3",
    "C1",
    "Cz",
    "C2",
    "C4",
    "C6",
]
temporal = ["FT7", "T7", "TP7", "FT8", "T8", "TP8"]
parietal = [
    "CP5",
    "CP3",
    "CP1",
    "CPz",
    "CP2",
    "CP4",
    "CP6",
    "P5",
    "P3",
    "P1",
    "Pz",
    "P2",
    "P4",
    "P6",
]
occipital = [
    "P7",
    "P8",
    "P9",
    "PO7",
    "PO3",
    "POz",
    "PO4",
    "PO8",
    "P10",
    "Oz",
    "Iz",
    "O1",
    "O2",
]
fronto-temporal = [
    "F7",
    "F5",
    "F3",
    "F1",
    "Fz",
    "F2",
    "F4",
    "F6",
    "F8",
    "FT7",
    "T7",
    "TP7",
    "FT8",
    "T8",
    "TP8",
]
fronto-central = [
    "F3",
    "F1",
    "Fz",
    "F2",
    "F4",
    "FC5",
    "FC3",
    "FC1",
    "FCz",
    "FC2",
    "FC4",
    "FC6",
]
centro-parietal = [
    "C5",
    "C3",
    "C1",
    "Cz",
    "C2",
    "C4",
    "C6",
    "CP5",
    "CP3",
    "CP1",
    "CPz",
    "CP2",
    "CP4",
    "CP6",
    "P5",
    "P3",
    "P1",
    "Pz",
    "P2",
    "P4",
    "P6",
]

[stim]
[stim.x_pos_stim]
# * Manually extracted from experiment's script
items_set = [
    -1042.222,
    -744.444,
    -446.667,
    -148.889,
    148.889,
    446.667,
    744.444,
    1042.222,
]

avail_choice = [
    -446.66700000000003,
    -148.88900000000012,
    148.88900000000012,
    446.6669999999999,
]
