[global]
expName = "Experiment_1-EasyAnalogy"
database_path = "./config/database.db"
feedback = true

[global.timings]
feedback_duration = 4
intertrial_interval = [1, 3]
pres_duration = 0.6
resp_window = 12

[global.pattern_IDs]
AAAAAAAA = 0
AAABAAAB = 1
AABBAABB = 2
AABBCCDD = 3
AABCAABC = 4
ABABABAB = 5
ABABCDCD = 6
ABACABAC = 7
ABBAABBA = 8
ABBACDDC = 9
ABBBABBB = 10
ABBCABBC = 11
ABCAABCA = 12
ABCCABCC = 13
ABCCBAAB = 14
ABCDABCD = 15
ABCDDCBA = 16
ABCDEABC = 17
ABCDEEDC = 18
ABCDEFAB = 19
ABCDEFGH = 20

[global.stim_IDs]
alarm-clock = 0
apps = 1
baby-carriage = 2
bell = 3
biking = 4
bone = 5
box-open = 6
sun = 7
broadcast-tower = 8
bulb = 9
camera = 10
candy-cane = 11
carrot = 12
chess = 13
club = 14
cocktail-alt = 15
cube = 16
diamond = 17
eye = 18
fish = 19
gamepad = 20
gift = 21
globe = 22
graduation-cap = 23
guitar = 24
hammer = 25
hand-horns = 26
headphones = 27
heart = 28
helicopter = 29
home = 30
ice-skate = 31
island-tropical = 32
key = 33
lock = 34
megaphone = 35
mug-hot-alt = 36
music-alt = 37
paper-plane = 38
paw = 39
peach = 40
phone-call = 41
plane-alt = 42
playing-cards = 43
pyramid = 44
rocket = 45
rugby = 46
search = 47
settings = 48
shopping-basket = 49
shopping_cart = 50
skiing = 51
smile = 52
social-network = 53
spade = 54
star = 55
trophy-star = 56
truck = 57
user = 58
wheat = 59

[lab]
allowed_keys = ["a", "x", "m", "l"]

[lab.EEG]
write_add = "0x4050"
read_add = "0x4051"

[lab.eye_tracker]
ip_add = "100.1.1.1"

[lab.event_IDs]
invalid = 10
a = 11
x = 12
m = 13
l = 14
timeout = 15
escape = 16
experiment_start = 21
experiment_aborted = 22
experiment_end = 23
block_start = 31
block_end = 32
trial_start = 41
trial_aborted = 42
trial_end = 43
stim-flash_sequence = 51
stim-flash_choices = 52
stim-all_stim = 53
error = 100
eeg_reset = 255

[lab.monitor]
name = "Main"
refresh_rate = 120
resolution = [2560, 1440]
notes = ""

[online]
