["meta-llama/Llama-3.2-3B-Instruct"]
layers = [
        "lm_head"
]

["Qwen/QwQ-32B-Preview"]
layers = [
        "lm_head"
]

["google/gemma-2-2b-it"]
layers = [
        "lm_head"
]

["google/gemma-2-9b-it"]
layers = [
        "lm_head"
]

[other_model]
layers = []