["google/gemma-2-2b-it"]
layers = [
        'model.layers.0',
        'model.layers.1',
        'model.layers.2',
        'model.layers.3',
        'model.layers.4',
        'model.layers.5',
        'model.layers.6',
        'model.layers.7',
        'model.layers.8',
        'model.layers.9',
        'model.layers.10',
        'model.layers.11',
        'model.layers.12',
        'model.layers.13',
        'model.layers.14',
        'model.layers.15',
        'model.layers.16',
        'model.layers.17',
        'model.layers.18',
        'model.layers.19',
        'model.layers.20',
        'model.layers.21',
        'model.layers.22',
        'model.layers.23',
        'model.layers.24',
        'model.layers.25',
]

["google/gemma-2-9b-it"]
layers = [
        'model.layers.0',
        'model.layers.1',
        'model.layers.2',
        'model.layers.3',
        'model.layers.4',
        'model.layers.5',
        'model.layers.6',
        'model.layers.7',
        'model.layers.8',
        'model.layers.9',
        'model.layers.10',
        'model.layers.11',
        'model.layers.12',
        'model.layers.13',
        'model.layers.14',
        'model.layers.15',
        'model.layers.16',
        'model.layers.17',
        'model.layers.18',
        'model.layers.19',
        'model.layers.20',
        'model.layers.21',
        'model.layers.22',
        'model.layers.23',
        'model.layers.24',
        'model.layers.25',
        'model.layers.26',
        'model.layers.27',
        'model.layers.28',
        'model.layers.29',
        'model.layers.30',
        'model.layers.31',
        'model.layers.32',
        'model.layers.33',
        'model.layers.34',
        'model.layers.35',
        'model.layers.36',
        'model.layers.37',
        'model.layers.38',
        'model.layers.39',
        'model.layers.40',
        'model.layers.41',
]

["Qwen/QwQ-32B-Preview"]
layers = ["model.layers.1", "model.layers.63"]

["Qwen/Qwen2.5-72B-Instruct"]
layers = [
        'model.layers.0',
        'model.layers.1',
        'model.layers.2',
        'model.layers.3',
        'model.layers.4',
        'model.layers.5',
        'model.layers.6',
        'model.layers.7',
        'model.layers.8',
        'model.layers.9',
        'model.layers.10',
        'model.layers.11',
        'model.layers.12',
        'model.layers.13',
        'model.layers.14',
        'model.layers.15',
        'model.layers.16',
        'model.layers.17',
        'model.layers.18',
        'model.layers.19',
        'model.layers.20',
        'model.layers.21',
        'model.layers.22',
        'model.layers.23',
        'model.layers.24',
        'model.layers.25',
        'model.layers.26',
        'model.layers.27',
        'model.layers.28',
        'model.layers.29',
        'model.layers.30',
        'model.layers.31',
        'model.layers.32',
        'model.layers.33',
        'model.layers.34',
        'model.layers.35',
        'model.layers.36',
        'model.layers.37',
        'model.layers.38',
        'model.layers.39',
        'model.layers.40',
        'model.layers.41',
        'model.layers.42',
        'model.layers.43',
        'model.layers.44',
        'model.layers.45',
        'model.layers.46',
        'model.layers.47',
        'model.layers.48',
        'model.layers.49',
        'model.layers.50',
        'model.layers.51',
        'model.layers.52',
        'model.layers.53',
        'model.layers.54',
        'model.layers.55',
        'model.layers.56',
        'model.layers.57',
        'model.layers.58',
        'model.layers.59',
        'model.layers.60',
        'model.layers.61',
        'model.layers.62',
        'model.layers.63',
        'model.layers.64',
        'model.layers.65',
        'model.layers.66',
        'model.layers.67',
        'model.layers.68',
        'model.layers.69',
        'model.layers.70',
        'model.layers.71',
        'model.layers.72',
        'model.layers.73',
        'model.layers.74',
        'model.layers.75',
        'model.layers.76',
        'model.layers.77',
        'model.layers.78',
        'model.layers.79',
]

['Qwen/Qwen2.5-7B-Instruct']
layers = ["model.layers.1", "model.layers.27"]

["Qwen/Qwen2.5-32B-Instruct"]
layers = []

["meta-llama/Llama-3.2-3B-Instruct"]
layers = [
        'model.layers.0',
        'model.layers.1',
        'model.layers.2',
        'model.layers.3',
        'model.layers.4',
        'model.layers.5',
        'model.layers.6',
        'model.layers.7',
        'model.layers.8',
        'model.layers.9',
        'model.layers.10',
        'model.layers.11',
        'model.layers.12',
        'model.layers.13',
        'model.layers.14',
        'model.layers.15',
        'model.layers.16',
        'model.layers.17',
        'model.layers.18',
        'model.layers.19',
        'model.layers.20',
        'model.layers.21',
        'model.layers.22',
        'model.layers.23',
        'model.layers.24',
        'model.layers.25',
        'model.layers.26',
        'model.layers.27',
]

["meta-llama/Meta-Llama-3-8B-Instruct"]
layers = ["model.layers.1", "model.layers.31"]

["meta-llama/Llama-3.3-70B-Instruct"]
layers = ["model.layers.1", "model.layers.79"]

["deepseek-ai/DeepSeek-R1-Distill-Llama-70B"]
# Based on Llama-3.3-70B-Instruct
layers = [
        'model.layers.0',
        'model.layers.1',
        'model.layers.2',
        'model.layers.3',
        'model.layers.4',
        'model.layers.5',
        'model.layers.6',
        'model.layers.7',
        'model.layers.8',
        'model.layers.9',
        'model.layers.10',
        'model.layers.11',
        'model.layers.12',
        'model.layers.13',
        'model.layers.14',
        'model.layers.15',
        'model.layers.16',
        'model.layers.17',
        'model.layers.18',
        'model.layers.19',
        'model.layers.20',
        'model.layers.21',
        'model.layers.22',
        'model.layers.23',
        'model.layers.24',
        'model.layers.25',
        'model.layers.26',
        'model.layers.27',
        'model.layers.28',
        'model.layers.29',
        'model.layers.30',
        'model.layers.31',
        'model.layers.32',
        'model.layers.33',
        'model.layers.34',
        'model.layers.35',
        'model.layers.36',
        'model.layers.37',
        'model.layers.38',
        'model.layers.39',
        'model.layers.40',
        'model.layers.41',
        'model.layers.42',
        'model.layers.43',
        'model.layers.44',
        'model.layers.45',
        'model.layers.46',
        'model.layers.47',
        'model.layers.48',
        'model.layers.49',
        'model.layers.50',
        'model.layers.51',
        'model.layers.52',
        'model.layers.53',
        'model.layers.54',
        'model.layers.55',
        'model.layers.56',
        'model.layers.57',
        'model.layers.58',
        'model.layers.59',
        'model.layers.60',
        'model.layers.61',
        'model.layers.62',
        'model.layers.63',
        'model.layers.64',
        'model.layers.65',
        'model.layers.66',
        'model.layers.67',
        'model.layers.68',
        'model.layers.69',
        'model.layers.70',
        'model.layers.71',
        'model.layers.72',
        'model.layers.73',
        'model.layers.74',
        'model.layers.75',
        'model.layers.76',
        'model.layers.77',
        'model.layers.78',
        'model.layers.79',
]

[other_model]
layers = []
